name: Continuous Integration

# Controls when the action will run.
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  glific:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # cypress setup
      - name: Setup cypress-testing
        uses: actions/checkout@v4

      - name: Use latest Node.js
        uses: actions/setup-node@v4

      # frontend setup
      - name: Setup frontend
        run: |
          echo '127.0.0.1  glific.test' | sudo tee -a /etc/hosts
          mkdir project
          cd project
          echo clone glific repo
          git clone https://github.com/glific/glific-frontend.git
          echo done. go to repo dir.
          cd glific-frontend
          echo copy env file.
          cp .env.example .env
          echo done.
          cat /proc/sys/fs/inotify/max_user_watches
          echo set watchers
          sudo sysctl fs.inotify.max_user_watches=524288
          sudo sysctl -p
          cat /proc/sys/fs/inotify/max_user_watches
          echo start yarn setup.
          yarn setup
          echo done.
          cd ../

        # Run frontend
      - name: run glific-frontend
        run: |
          cd /home/runner/work/cypress-testing/cypress-testing/project/glific-frontend
          yarn dev &

      - name: Wait for frontend to start
        run: |
          sleep 1m

        # Run cypress
      - name: Cypress run
        run: |
          echo Create cypress.config.ts from example
          cp cypress.config.ts.example cypress.config.ts
          yarn install
          yarn run cypress run --record --key ${{ secrets.CYPRESS_DASHBOARD_KEY }}
