name: Stagging - Continuous Integration

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # cypress setup
      - name: Setup cypress-testing
        run: |
          ls
          pwd
          echo go to dir.
          cd cypress-testing
          ls
          pwd
          echo Copy Cypress.json from example
          cp cypress-stagging.json.example cypress.json

      # Run cypress
      - name: Cypress run
        run: |
          ls
          pwd
          cd /home/runner/work/cypress-testing/cypress-testing/cypress-testing
          yarn install
          yarn cy:run
