name: Staging - Continuous Integration

# Controls when the action will run. Triggers the workflow on push or pull request
# schedule cron at 00:00 UTC means 5:30 am IST
# events but only for the main branch
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # cypress setup
      - name: Setup cypress-testing
        run: |
          echo Copy Cypress.json from example
          cp cypress-staging.json.example cypress.json

      # Run cypress
      - name: Cypress run
        run: |
          yarn install
          yarn cy:run --record --key ${{ secrets.CYPRESS_DASHBOARD_KEY }}
